# Generated by Django 3.2.8 on 2021-10-22 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211010_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('teacher_first_name', models.CharField(max_length=30)),
                ('teacher_last_name', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('class_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_student', models.CharField(max_length=10)),
                ('receiving_student', models.CharField(max_length=10)),
                ('request_status', models.CharField(default='U', max_length=1)),
            ],
            options={
                'db_table': 'friend requests',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_student_username', models.CharField(max_length=10)),
                ('second_student_username', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'friendships',
            },
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
