# Generated by Django 3.1.7 on 2021-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211022_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.CharField(default='Lynbrook HS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='Lynbrook HS', max_length=50),
            preserve_default=False,
        ),
    ]
